steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/present:$COMMIT_SHA, '.']
- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/present:$COMMIT_SHA]
- name: acoshift/kubectl
  args: [set, image, deploy/present, app=gcr.io/$PROJECT_ID/present:$COMMIT_SHA]
  env:
  - SERVER=$_DEPLOY_ENDPOINT
  - NAMESPACE=$_DEPLOY_NAMESPACE
  - TOKEN=$_DEPLOY_TOKEN
images:
  - gcr.io/$PROJECT_ID/present:$COMMIT_SHA
