steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/present:$COMMIT_SHA, '.']
- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/present:$COMMIT_SHA]
- name: gcr.io/cloud-builders/gcloud
  args: [beta, run, deploy, $_RUN_NAME, --region=$_RUN_REGION, --image, gcr.io/$PROJECT_ID/present:$COMMIT_SHA]
images:
  - gcr.io/$PROJECT_ID/present:$COMMIT_SHA
