apiVersion: v1
kind: ConfigMap
metadata:
  name: postlist
  labels:
    app: postlist
data:
  sqlurl: postgres://root@cockroachdb-public:26257/postlist?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: postlist
  labels:
    app: postlist
spec:
  ports:
  - port: 8080
  selector:
    app: postlist
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postlist
  labels:
    app: postlist
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postlist
  template:
    metadata:
      name: postlist
      labels:
        app: postlist
    spec:
      containers:
      - name: postlist
        image: gcr.io/acoshift-k8s/postlist:1.0.0
        ports:
        - containerPort: 8080
        livenessProbe: &probe
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 5
        readinessProbe: *probe
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /config
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: postlist
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: postlist
  labels:
    app: postlist
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postlist
